### PR TITLE
Improved CSS and updated team

### PR DESCRIPTION
**Pull request by AyushSrivastava0609**
Removed the scroll bar appearance from the community section and fixed the top margin in the css topic section of technotes , Also updated the team by adding a new member : Avanish yadav
I have also updated the sidebar of the news section to make it look more visually appealing
I have also updated the headings of Team and Community Section to make it look more beautiful i.e. added gradient colors to it

### CODE REVIEW

**Comment by lambaaryan011** [comment]
bro the issue(fixed the top margin in the css topic section of technotes) is solve my 3 hour age

**Comment by lambaaryan011** [comment]
bro this  issue ( fixed the top margin in the css topic section of technotes) is solved

**Comment by AyushSrivastava0609** [comment]
> bro this issue ( fixed the top margin in the css topic section of technotes) is solved

it was my section to edit and render , i think you are misunderstanding this thing for something else

**Comment by Pinti0001** [comment]
> Removed the scroll bar appearance from the community section and fixed the top margin in the css topic section of technotes , Also updated the team by adding a new member : Avanish yadav I have also updated the sidebar of the news section to make it look more visually appealing I have also updated the headings of Team and Community Section to make it look more beautiful i.e. added gradient colors to it

@AyushSrivastava0609  Please also give a photo of how the UI looks after changing, so that it will be easier to understand.

**Pull request merged**
